FROM python:3.11

WORKDIR /code4

COPY ./requirement.txt /code/requirement.txt

RUN pip install --no-cache-dir -r /code/requirement.txt

COPY ./app  /code/app

EXPOSE 8000

CMD ["uvicorn","app.server:app","--host","0.0.0.0","--port","8000"]
